# .github/workflows/deploy.yml
name: Deploy PR previews
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize    
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.4.3
        with:
          token: ${{ secrets.PREVIEW_TOKEN }}
          source-dir: .
          umbrella-dir: pr-preview
          action: auto